provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  faas-service:
    lang: python3-flask-debian
    handler: ./function
    image: localhost:5000/faas-service:latest
    min_replicas: 1
    build_args:
      ADDITIONAL_PACKAGE: ""
    environment:
      DIAGNOSTICS: "false"

